name: Build Switch Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: "Tag of the new image (usually the date: YYYYMMDD)"
      custom_ref:
        required: false
        description: "Commit ref that contains the Dockerfile you want to use (if left blank: master HEAD)"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.custom_ref }}

    - name: Login to Docker Hub Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build/Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: misc/ci/Dockerfile.switch
        push: true
        tags: taiseiproject/switch-toolkit:${{ github.event.inputs.image_tag }}
